version: '3.8'

services:
  # Backend API Service
  api-erp:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    env_file:
      - .env
    networks:
      - tunnel
    restart: unless-stopped

networks:
  tunnel:
    external: true
