const NON_CURENT_ASSETS_TYPE = {
  VEHICLE: 'VEHICLE',
  BUILDING: 'BUILDING',
  LAND: 'LAND',
  LONG_TERM_INVESTMENT: 'LONG_TERM_INVESTMENT',
  OTHERS: 'OTHERS',
};

const NON_CURENT_ASSETS_TYPE_LIST = Object.values(NON_CURENT_ASSETS_TYPE);

module.exports = {
  NON_CURENT_ASSETS_TYPE,
  NON_CURENT_ASSETS_TYPE_LIST,
}